package Harjoitustyo.test;
// Generated by ComTest BEGIN
import Harjoitustyo.Jaos;
import static org.junit.Assert.*;
import org.junit.*;
import static Harjoitustyo.Jaos.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.20 18:43:29 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class JaosTest {



  // Generated by ComTest BEGIN
  /** testMain122 */
  @Test
  public void testMain122() {    // Jaos: 122
    Jaos j = new Jaos(); 
    assertEquals("From: Jaos line: 125", "Jaokselle ei ole määritelty nimeä!", j.getNimi()); 
    assertEquals("From: Jaos line: 126", "Jaokselle ei ole määritelty tehtävää!", j.getTehtava()); 
    j.lisaaNimi("Pulla5"); 
    assertEquals("From: Jaos line: 128", "Pulla5", j.getNimi()); 
    j.lisaaTehtava("Rötvääminen"); 
    assertEquals("From: Jaos line: 130", "Rötvääminen", j.getTehtava()); 
    assertEquals("From: Jaos line: 131", 0, j.getJid()); 
    j.lisaajid(5); 
    assertEquals("From: Jaos line: 133", 5, j.getJid()); 
    j.lisaaRyhma(1); 
    assertEquals("From: Jaos line: 135", 1, j.getRyhmaLkm()); 
    j.poistaRyhma(1); 
    assertEquals("From: Jaos line: 137", 0, j.getRyhmaLkm()); 
  } // Generated by ComTest END
}