package Harjoitustyo.test;
// Generated by ComTest BEGIN
import Harjoitustyo.Jasenet;
import static org.junit.Assert.*;
import org.junit.*;
import static Harjoitustyo.Jasenet.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.20 19:11:05 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class JasenetTest {



  // Generated by ComTest BEGIN
  /** testMain209 */
  @Test
  public void testMain209() {    // Jasenet: 209
    Jasenet j = new Jasenet(); 
    assertEquals("From: Jasenet line: 212", 0, j.getJasentenlkm()); 
  } // Generated by ComTest END
}