package Harjoitustyo.test;
// Generated by ComTest BEGIN
import Harjoitustyo.Jasen;
import static org.junit.Assert.*;
import org.junit.*;
import static Harjoitustyo.Jasen.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.06 13:37:56 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class JasenTest {



  // Generated by ComTest BEGIN
  /** testMain46 */
  @Test
  public void testMain46() {    // Jasen: 46
    Jasen lohi = new Jasen(); 
    assertEquals("From: Jasen line: 49", 0, lohi.getRid()); 
    assertEquals("From: Jasen line: 50", 0, lohi.getSid()); 
    assertEquals("From: Jasen line: 51", "", lohi.getEtuNimi()); 
    assertEquals("From: Jasen line: 52", "", lohi.getSukuNimi()); 
    assertEquals("From: Jasen line: 53", 0, lohi.getSyntymaAikaPv()); 
    assertEquals("From: Jasen line: 54", 0, lohi.getSyntymaAikaKk()); 
    assertEquals("From: Jasen line: 55", 0, lohi.getSyntymaAikaVv()); 
    lohi.lisaaNimi("Eetu", "Lohi"); 
    assertEquals("From: Jasen line: 57", "Eetu", lohi.getEtuNimi()); 
    assertEquals("From: Jasen line: 58", "Lohi", lohi.getSukuNimi()); 
    lohi.lisaaTehtava("Runnutus"); 
    assertEquals("From: Jasen line: 60", "Runnutus", lohi.getTehtava()); 
    lohi.lisaaSyntymaAika(1,7,1600); 
    assertEquals("From: Jasen line: 62", 1, lohi.getSyntymaAikaPv()); 
    assertEquals("From: Jasen line: 63", 7, lohi.getSyntymaAikaKk()); 
    assertEquals("From: Jasen line: 64", 1600, lohi.getSyntymaAikaVv()); 
    lohi.lisaaAseNro(69420666); 
    assertEquals("From: Jasen line: 66", 69420666, lohi.getAseenNumero()); 
    lohi.lisaaLisatieto("Gonaukko"); 
    assertEquals("From: Jasen line: 68", "Gonaukko", lohi.getLisatieto()); 
    lohi.lisaaArvo("Mosa"); 
    assertEquals("From: Jasen line: 70", "Mosa", lohi.getArvo()); 
  } // Generated by ComTest END
}